name: rasseed
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_statusbarcolor: ^0.2.2
  country_code_picker: ^1.1.5
  flip_card: ^0.4.4
  sms_autofill: ^1.1.1
  flutter_staggered_grid_view: "^0.2.7"
  flutter_cupertino_localizations: ^1.0.1
  flutter_localizations:
    sdk: flutter
  grouped_buttons: ^1.0.4
  http:
  xs_progress_hud: ^1.0.2
  flushbar:
  simple_animations:
  shared_preferences:
  flutter_slidable: "^0.5.3"
  unicorndial: ^1.1.5
  share:
  webview_flutter: ^0.3.14+1
  flutter_webview_plugin: 0.3.0+2
  cached_network_image: ^1.1.3
  carousel_slider: ^1.3.0
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image.png
    - assets/image1.png
    - assets/image2.png
    - assets/image3.png
    - assets/image4.png
    - assets/350.png
    - lang/ar.json
    - lang/en.json

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  fonts:
    - family: Cairo
      fonts:
        - asset: Font/Cairo-Regular.ttf
        - asset: Font/Cairo-Bold.ttf
    - family: Roboto
      fonts:
        - asset: Font/Roboto/Roboto-Black.ttf
        - asset: Font/Roboto/Roboto-BlackItalic.ttf
        - asset: Font/Roboto/Roboto-Bold.ttf
        - asset: Font/Roboto/Roboto-BoldItalic.ttf
        - asset: Font/Roboto/Roboto-Italic.ttf
        - asset: Font/Roboto/Roboto-Light.ttf
        - asset: Font/Roboto/Roboto-LightItalic.ttf
        - asset: Font/Roboto/Roboto-Medium.ttf
        - asset: Font/Roboto/Roboto-MediumItalic.ttf
        - asset: Font/Roboto/Roboto-Regular.ttf
        - asset: Font/Roboto/Roboto-Thin.ttf
        - asset: Font/Roboto/Roboto-ThinItalic.ttf
  # fonts:
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
